PDF := operator-algebra-modular-theory-and-quantum-gravity.pdf
JOBNAME := $(basename $(PDF))

TEX_SOURCES := \
	$(wildcard chapters/*.tex) \
	$(wildcard parts/*.tex) \
	$(wildcard appendices/*.tex) \
	preamble.tex \
	macros.tex \
	refs.bib

.PHONY: all pdf ch clean

all: pdf

pdf: $(PDF)

# main.tex is generated by scripts/gen.py.
main.tex: scripts/gen.py $(TEX_SOURCES)
	python3 scripts/gen.py

$(PDF): main.tex
	latexmk -pdf \
		-interaction=nonstopmode \
		-halt-on-error \
		-file-line-error \
		-jobname=$(JOBNAME) \
		main.tex

# Build a single chapter quickly: make ch N=10
ch:
	python3 scripts/chapter_only.py $(N)

clean:
	if [ -f main.tex ]; then latexmk -C -jobname=$(JOBNAME) main.tex; fi

