#!/usr/bin/env python3
"""Generate main.tex and any MISSING chapter stubs from scripts/*.tsv.
Never overwrites an existing chapter file.  Run: python3 scripts/gen.py"""
import os
root=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
chs=[l.rstrip('\n').split('\t') for l in open(f'{root}/scripts/chapters.tsv') if l.strip()]
parts=[l.rstrip('\n').split('\t') for l in open(f'{root}/scripts/parts.tsv') if l.strip()]
info={int(n):(slug,title,tier) for n,slug,title,tier in chs}
def fname(n): return f"ch{n:02d}_{info[n][0]}"
for n in info:
    p=f"{root}/chapters/{fname(n)}.tex"
    if not os.path.exists(p):
        slug,title,tier=info[n]
        skip = "\\skippable\n" if tier=='skip' else ""
        open(p,'w').write(f"""% STATUS: STUB
\\chapter{{{title}}}\\label{{ch:{slug}}}
{skip}
\\begin{{physmotiv}}
TODO
\\end{{physmotiv}}

\\section{{TODO}}
TODO

\\section*{{Exercises}}
TODO
""")
out=[r"""% AUTO-GENERATED by scripts/gen.py  (edit scripts/*.tsv, not this file's chapter list)
\documentclass[11pt,a4paper,openany]{book}
\input{preamble}
\input{macros}
\title{\textbf{Operator Algebras, Modular Theory, and Quantum Gravity}\\[0.4em]
\large A Physicist's Guide}
\author{Draft}
\date{\today}
\begin{document}
\frontmatter
\maketitle
\input{frontmatter/preface}
\tableofcontents
\mainmatter
"""]
for roman,title,a,b in parts:
    out.append(f"\\part{{{title}}}\n")
    for n in range(int(a),int(b)+1):
        out.append(f"\\input{{chapters/{fname(n)}}}\n")
    pf=f"parts/part{roman}_dictionary"
    if os.path.exists(f"{root}/{pf}.tex"):
        out.append(f"\\input{{{pf}}}\n")
out.append(r"""\appendix
\input{appendices/appendices}
\backmatter
\bibliographystyle{unsrtnat}
\bibliography{refs}
\end{document}
""")
open(f'{root}/main.tex','w').write(''.join(out))
print("generated main.tex;", len(info),"chapters")
