#!/usr/bin/env python3
"""Generate main.tex from scripts/chapters.tsv and scripts/parts.tsv.
Columns of chapters.tsv: number, slug, title, tier(core|skip), merged source topics.
Chapter files are chapters/chNN_slug.tex.  Run: python3 scripts/gen.py"""
import os
root=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
chs=[l.rstrip('\n').split('\t') for l in open(f'{root}/scripts/chapters.tsv') if l.strip()]
parts=[l.rstrip('\n').split('\t') for l in open(f'{root}/scripts/parts.tsv') if l.strip()]
info={int(c[0]):c[1] for c in chs}
for n,slug in info.items():
    p=f"{root}/chapters/ch{n:02d}_{slug}.tex"
    if not os.path.exists(p): raise SystemExit(f"missing chapter file {p}")
out=[r"""% AUTO-GENERATED by scripts/gen.py  (edit scripts/*.tsv, not this file's chapter list)
\documentclass[10pt,twoside,openany]{book}
\input{preamble}
\input{macros}
\title{Operator Algebras, Modular Theory, and Quantum Gravity}
\author{}
\date{}
\begin{document}
\frontmatter
\input{frontmatter/titlepage}
\input{frontmatter/preface}
\tableofcontents
\mainmatter
\setcounter{part}{-1}
"""]
for roman,title,a,b in parts:
    out.append(f"\\part{{{title}}}\n")
    for n in range(int(a),int(b)+1):
        out.append(f"\\input{{chapters/ch{n:02d}_{info[n]}}}\n")
    pf=f"parts/part{roman}_dictionary"
    if os.path.exists(f"{root}/{pf}.tex"):
        out.append(f"\\input{{{pf}}}\n")
out.append(r"""\appendix
\input{appendices/appendices}
\backmatter
\bibliographystyle{unsrtnat}
\bibliography{refs}
\printindex
\end{document}
""")
open(f'{root}/main.tex','w').write(''.join(out))
print("generated main.tex;",len(info),"chapters")
